### PR TITLE
fix(vis): scatter plot legend toggle for splom

### LINKED ISSUE #771: Scatter plot: Wrong filter from legend for scatter pot matrix
The filtering works as expected for the facet mode.

[scatterplot-filter-legend.webm](https://github.com/user-attachments/assets/71c65ece-a742-4563-a8ed-af605eab3dfd)

However, it does not work for the matrix mode.

image

I'd expect to see only the gray unknown points in this screenshot.

_Originally posted by @thinkh in https://github.com/datavisyn/visyn_core/issues/770#issuecomment-2761290237_

### PR DESCRIPTION
**Pull request by dv-usama-ansari**
Closes #771 

### Developer Checklist (Definition of Done)

**Issue**

- [x] All acceptance criteria from the issue are met
- [x] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [x] Requires UI/UX/Vis review
  - [x] Reviewer(s) are notified @dvmoritzschoefl 
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [x] Branch is up-to-date with the branch to be merged with, i.e., develop
- [x] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [x] Descriptive title for this pull request is provided (will be used for release notes later)
- [x] Reviewer and assignees are defined
- [x] Add type label (e.g., *bug*, *feature*) to this pull request
- [x] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [x] The PR is connected to the corresponding issue (via `Closes #...`)
- [x] [Summary of changes](#summary-of-changes) is written

### Summary of changes

- Fixed legend toggle in scatter plot

### Screenshots

https://github.com/user-attachments/assets/04c7a2f9-66c1-4ed0-9cd7-bca881cb7e27

### Additional notes for the reviewer(s)
- N/A

### CODE REVIEW

File: src/vis/scatter/useData.tsx [hunk 1]
```diff
@@ -249,8 +249,11 @@ export function useData({
           ...(isEmpty(selectedSet) ? {} : { selectedpoints: selectedList.map((idx) => splom.idToIndex.get(idx)) }),
           marker: {
             size: 8,
-            color: value.colorColumn && mappingFunction ? value.colorColumn.resolvedValues.map((v) => mappingFunction(v.val)) : VIS_NEUTRAL_COLOR,
-            symbol: value.shapeColumn ? value.shapeColumn.resolvedValues.map((v) => shapeScale(v.val as string)) : 'circle',
+            color:
+              value.colorColumn && mappingFunction
```
Comment (dv-usama-ansari) [inline src/vis/scatter/useData.tsx:253]: Using the color from `filter` object of the splom. This is now consistent with the other scatter configurations

**Review by dvmoritzschoefl — APPROVED** [review]
