### PR TITLE
Fix: tooltip bug in violin plot

### LINKED ISSUE #135: VIS Bug: Violin plot hover-over stops working due to null values
### Steps to reproduce the bug

1. Open a violin plot and chose a column that contains null values for a numerical column

### Observed Behavior
- Hover is broken when the data has null values and we get the following console error:
image

### Expected Behavior
Null values are removed from the violin plot at all as they don't add any value to the visualization and currently they even break it.

### How to reproduce it in visyn_core storybook:
1. Replace [this line](https://github.com/datavisyn/visyn_core/blob/5d8beaa5ca66952ae8159c908ebdbf993423a076/src/vis/stories/fetchIrisData.tsx#L13) by: `values: () => dataPromise.map((r) => r.sepalLength).map((val, i) => ({ id: i.toString(), val: i < 10 ? val : null }))` to have a lot of null values in the data
2. Open the violin plot in storybook and hover over it. You won't see any tooltip and a console error:
image

Thanks for taking the time to fill out this bug report 🤗
Make sure there aren't any open/closed issues for this topic 😃

### PR DESCRIPTION
**Pull request by dvdanielamoitzi**
Closes #135 

### Developer Checklist (Definition of Done)

**Issue**

- [x] All acceptance criteria from the issue are met
- [x] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [ ] Requires UI/UX/Vis review
  - [ ] Reviewer(s) are notified (_tag assignees_)
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [x] Branch is up-to-date with the branch to be merged with, i.e., develop
- [x] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [x] Descriptive title for this pull request is provided (will be used for release notes later)
- [x] Reviewer and assignees are defined
- [x] Add type label (e.g., *bug*, *feature*) to this pull request
- [ ] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [x] The PR is connected to the corresponding issue (via `Closes #...`)
- [x] [Summary of changes](#summary-of-changes) is written

### Summary of changes

- Removing all null values of the plots in the traces (affected props: x, y, ids, transform). In the below screencast, the upper plot contains lots of null values, and as you can see the tooltips are showing up again.

### Screenshots
[Screencast from 2024-01-09 19:21:23.webm](https://github.com/datavisyn/visyn_core/assets/57343176/25bb31bc-4a02-4725-8833-09072cc71ba4)

### Additional notes for the reviewer(s)

-  
Thanks for creating this pull request 🤗

### CODE REVIEW

File: src/vis/violin/ViolinVis.tsx [hunk 1]
```diff
@@ -19,6 +19,32 @@ export function ViolinVis({ config, columns, scales, dimensions, selectedList, s
...
+            ids: p.data?.ids?.filter((v, i) => !indexWithNull[p_index].includes(i)),
+            // @ts-ignore
+            transforms: p.data?.transforms?.map((t) => t.groups?.filter((v, i) => !indexWithNull[p_index].includes(i))),
+          },
+        };
+      }),
+    };
+    return filtered;
+  }, [traces]);
+
```
Comment (dv-usama-ansari) [inline src/vis/violin/ViolinVis.tsx:47]: I made some changes in the types to remove `// @ts-ignore` comments here: https://github.com/datavisyn/visyn_core/compare/dmoitzi/135_tooltip-bug-in-violin-plot...ua/135-vis-bug-violin-plot#diff-bd3a75a74b6e0db8c49e1a1894636abb0988458203cb80d6b8a0113ee1e7a849

**Review by dv-usama-ansari — COMMENTED** [review]
Thank you for your changes, this works as expected for me

File: src/vis/violin/ViolinVis.tsx (hunk 1 above)
Comment (dv-usama-ansari) [reply src/vis/violin/ViolinVis.tsx]: Resolved in https://github.com/datavisyn/visyn_core/pull/140/commits/0f2cf4b0f919232fb578e7fc6b0a3ab9a6b5095c

**Review by dv-usama-ansari — APPROVED** [review]
Thank you for the changes! With your confirmation that this works in bioinsight, it is safe to merge this PR
